#!/bin/bash

set -e  # Fail immediately if any of the commands below fail

if [ "$#" != "1" ]; then
    echo \
"Usage: $0 /dev/sdX

Checks if disk /dev/sdX is OK to be used."
    exit 0
fi

if [ ${EUID:-$UID} -gt 500 ]; then
    echo "Error: You are not root."
    exit 1
fi

DISK="$1"
LOG_FILE="disk_serials.txt"

indent() { sed 's/^/    /'; }

echo "Running S.M.A.R.T short test on: $DISK"
smartctl --smart on --badsum exit --captive --test short --quietmode errorsonly $DISK
if sudo smartctl --health --quietmode errorsonly $DISK; then
    echo "Health-check PASSED"
else
    echo "Health-check FAILED"
    exit 1
fi

get_smart_attributes() {
    smartctl --all $DISK |
        awk '/Reallocated_Sector|Current_Pending_Sector|Bad_Block|Uncorrectable/{ print $0 }'
}

# Sum all critical attribute values
bad_value=$(get_smart_attributes | awk '{ print $10 }' |
            paste -sd+ |
            bc)

# If bad attributes' values below threshold
if [ $bad_value -le 0 ]; then
    # Disk is OK, print out info and also append it to LOG_FILE
    echo ''
    smartctl --info $DISK |
        awk '/^Device Model|Serial Number|User Capacity/{ print $0 }END{ print "\n" }' |
        tee -a "$LOG_FILE"
    echo "(also appended to $LOG_FILE)"
else
    echo "Disk is NOT OK; SMART data:"
    echo "$(get_smart_attributes)" | indent
    exit 1
fi
