#!/bin/sh

set -e  # Fail immediately if any of the commands below fail

DEPENDENCIES="
coreutils
sed
# for wipe_disk
openssl
pv
# for asses_disk
smartmontools
bc
# for copy_image
python-yaml
parted
e2fsprogs
mount
util-linux
# for create_image
debootstrap
"

PACKAGES="$(echo "$DEPENDENCIES" | awk '/^ *[^# ]/{print $1}')"

echo "Installing packages: "$PACKAGES

apt-get install $PACKAGES
